### ISSUE TITLE
Can I use this plugin to detect mice sleep spindle?

### ISSUE THREAD

**Issue by jiadeL** [stuartfogel/detect_spindles#1]
Can I use this plugin to detect mice sleep spindle?

**Comment by stuartfogel** [comment]
Hello,

In theory, you should be able to use the detector to identify any phasic event in the EEG that has a prescribed frequency.

I have used it in rats, and it works well, but the results are not published.

I have not used it in mice before, but, it might be possible.

There is a sample human PSG file available in the Git repository.

Best,

==
Stuart Fogel
Associate Professor | Professeur agrégé
Sleep Research Laboratory | Laboratoire de Sommeil
School of Psychology | École de psychologie
Room 3019 Vanier Hall | Salle 3019 Pavillion Vanier
University of Ottawa | Université d'Ottawa
Ottawa | Ontario | Canada | K1N 6N5
(613) 562-5800 x4295
***@***.******@***.***>

socialsciences.uottawa.ca/sleep-lab/
==

On May 26, 2022, at 3:57 PM, jiadeL ***@***.******@***.***>> wrote:

Attention : courriel externe | external email


Can I use this plugin to detect mice sleep spindle?

**Comment by jiadeL** [comment]
Thank you, Stuart！
