### ISSUE TITLE
Too many output arguments in DS_deleteDuplicates

### ISSUE THREAD

**Issue by yanzastro** [stuartfogel/detect_spindles#2]
Dear Stuart, I'm using your detect_spindles code on our data. However, I got an error "Too many output arguments" when I run `DS_deleteDuplicates` (please see the attached figure). When I checked `DS_deleteDuplicates.m`, I found the function is defined without an output. I'm wondering if it should be something like `function EEG=DS_deleteDuplicates(EEG)`? Thanks in advance!
<img width="567" alt="Weixin Image_20231212230408" src="https://github.com/stuartfogel/detect_spindles/assets/19143403/30e0c194-28fc-4834-b47c-7d04cd0fab32">

**Comment by stuartfogel** [comment]
Hello,

Thanks for identifying that. This was the newest feature and not yet extensively tested.
Yes, your suggested revision should do the trick. I will be revising and testing the code, an updated version 3.3.4 should be available very soon.

Best,

==
Stuart Fogel
Associate Professor | Professeur agrégé
Sleep Research Laboratory | Laboratoire de Sommeil
School of Psychology | École de psychologie
Room 3019 Vanier Hall | Salle 3019 Pavillion Vanier
University of Ottawa | Université d'Ottawa
Ottawa | Ontario | Canada | K1N 6N5
(613) 562-5800 x4295
***@***.***

socialsciences.uottawa.ca/sleep-lab/
==

From: yanzastro ***@***.***>
Date: Tuesday, December 12, 2023 at 11:05 PM
To: stuartfogel/detect_spindles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stuartfogel/detect_spindles] Too many output arguments in DS_deleteDuplicates (Issue #2)
Attention : courriel externe | external email

Dear Stuart, I'm using your detect_spindles code on our data. However, I got an error "Too many output arguments" when I run DS_deleteDuplicates (please see the attached figure). When I checked DS_deleteDuplicates.m, I found the function is defined without an output. I'm wondering if it should be something like function EEG=DS_deleteDuplicates(EEG)? Thanks in advance!
Weixin.Image_20231212230408.png (view on web)<https://github.com/stuartfogel/detect_spindles/assets/19143403/30e0c194-28fc-4834-b47c-7d04cd0fab32>
